
name: ums-stack
services:
    web-nginx:
      image: nginx:latest
      container_name: ums-nginx
      ports:
       - "8080:8080"
      depends_on:
        app-ums:
           condition: service_healthy
           restart: true
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      networks:
        - frontend
      healthcheck:
        test: ["CMD" , "curl","-f" ,"http://localhost:8080/nginx-health"]
        interval: 30s
        timeout: 10s
        retries: 3
    app-ums:
        image: ranjitgaikwad/usermgmt-webapp-v6:latest
        ports:
         - "8080"
        deploy:
          replicas: 1
        depends_on:
          db-mysql:
             condition: service_healthy
             restart: true
        environment:
          - DB_HOSTNAME=db-mysql
          - DB_PORT=3306
          - DB_NAME=webappdb
          - DB_USERNAME=root
          - DB_PASSWORD=dbpassword11
        networks:
          - frontend
          - backend
        healthcheck:
         test: ["CMD" ,"curl","-f" ,"http://localhost:8080/health"]
         interval: 30s
         timeout: 10s
         retries: 3
    db-mysql:
      container_name: ums-mysqldb
      image: mysql:8.0
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: dbpassword11
        MYSQL_DATABASE: webappdb
      ports:
       - "3306:3306"
      volumes:
       - mydb:/var/lib/mysql
      networks:
       - backend
      healthcheck:
       test: ["CMD" , "mysqladmin" , "ping" , "-h" ,"localhost", "-u" ,"root","-pdbpassword11"]
       interval: 30s
       timeout: 10s
       retries: 3

volumes:
  mydb:

networks:
 frontend:
 backend:

         